//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Customer
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Customer :
        global::LightSwitchApplication.Customer.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDisplayNameChanged()
        {
            this.___OnPropertyChanged("DisplayName");
        }
        
        partial void OnFNameChanged()
        {
            this.___OnPropertyChanged("FName");
        }
        
        partial void OnLNameChanged()
        {
            this.___OnPropertyChanged("LName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnGIDChanged()
        {
            this.___OnPropertyChanged("GID");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Customer.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> __Devices
        {
            get
            {
                if (this.___Devices == null)
                {
                    this.___Devices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device>(
                        this,
                        "Devices",
                        () => this._Devices,
                        e => global::System.Object.Equals(e.Device_Client, this.Id));
                }
                return this.___Devices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> ___Devices;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Customer.DetailsClass.IImplementation.HwSwOrders
        {
            get
            {
                return this.HwSwOrders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HwSwOrder> __HwSwOrders
        {
            get
            {
                if (this.___HwSwOrders == null)
                {
                    this.___HwSwOrders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HwSwOrder>(
                        this,
                        "HwSwOrders",
                        () => this._HwSwOrders,
                        e => global::System.Object.Equals(e.HwSwOrder_Client, this.Id));
                }
                return this.___HwSwOrders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.HwSwOrder> ___HwSwOrders;
        
    }
    #endregion
    
    #region Device
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Device :
        global::LightSwitchApplication.Device.DetailsClass.IImplementation
    {
        partial void OnDevice_MakeModelChanged()
        {
            this.___OnPropertyChanged("Device_MakeModel");
            this.___OnPropertyChanged("MakeModel");
        }
        
        partial void OnHwSwOrder_DeviceChanged()
        {
            this.___OnPropertyChanged("HwSwOrder_Device");
            this.___OnPropertyChanged("HwSwOrder");
        }
        
        partial void OnDevice_ClientChanged()
        {
            this.___OnPropertyChanged("Device_Client");
            this.___OnPropertyChanged("Owner");
        }
        
        partial void OnDevice_DeviceStatusChanged()
        {
            this.___OnPropertyChanged("Device_DeviceStatus");
            this.___OnPropertyChanged("DeviceStatus");
        }
        
        partial void OnDevice_StockLocationChanged()
        {
            this.___OnPropertyChanged("Device_StockLocation");
            this.___OnPropertyChanged("StockLocation");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnIMEIChanged()
        {
            this.___OnPropertyChanged("IMEI");
        }
        
        partial void OnSIMChanged()
        {
            this.___OnPropertyChanged("SIM");
        }
        
        partial void OnSerialChanged()
        {
            this.___OnPropertyChanged("Serial");
        }
        
        partial void OnPhoneNumberChanged()
        {
            this.___OnPropertyChanged("PhoneNumber");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.MakeModel
        {
            get
            {
                return this.MakeModel;
            }
            set
            {
                this.MakeModel = (global::LightSwitchApplication.Implementation.MakeModel)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MakeModel> __MakeModel
        {
            get
            {
                if (this.___MakeModel == null)
                {
                    this.___MakeModel = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MakeModel>(
                        this,
                        "MakeModel",
                        new string[] { "Device_MakeModel" },
                        e => global::System.Object.Equals(e.Id, this.Device_MakeModel),
                        () => this._MakeModel,
                        e => this._MakeModel = e);
                }
                return this.___MakeModel;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MakeModel> ___MakeModel;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.HwSwOrder
        {
            get
            {
                return this.HwSwOrder;
            }
            set
            {
                this.HwSwOrder = (global::LightSwitchApplication.Implementation.HwSwOrder)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HwSwOrder> __HwSwOrder
        {
            get
            {
                if (this.___HwSwOrder == null)
                {
                    this.___HwSwOrder = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HwSwOrder>(
                        this,
                        "HwSwOrder",
                        new string[] { "HwSwOrder_Device" },
                        e => global::System.Object.Equals(e.Id, this.HwSwOrder_Device),
                        () => this._HwSwOrder,
                        e => this._HwSwOrder = e);
                }
                return this.___HwSwOrder;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.HwSwOrder> ___HwSwOrder;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.Owner
        {
            get
            {
                return this.Owner;
            }
            set
            {
                this.Owner = (global::LightSwitchApplication.Implementation.Customer)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> __Owner
        {
            get
            {
                if (this.___Owner == null)
                {
                    this.___Owner = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer>(
                        this,
                        "Owner",
                        new string[] { "Device_Client" },
                        e => global::System.Object.Equals(e.Id, this.Device_Client),
                        () => this._Owner,
                        e => this._Owner = e);
                }
                return this.___Owner;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> ___Owner;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.DeviceStatus
        {
            get
            {
                return this.DeviceStatus;
            }
            set
            {
                this.DeviceStatus = (global::LightSwitchApplication.Implementation.DeviceStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DeviceStatus> __DeviceStatus
        {
            get
            {
                if (this.___DeviceStatus == null)
                {
                    this.___DeviceStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DeviceStatus>(
                        this,
                        "DeviceStatus",
                        new string[] { "Device_DeviceStatus" },
                        e => global::System.Object.Equals(e.Id, this.Device_DeviceStatus),
                        () => this._DeviceStatus,
                        e => this._DeviceStatus = e);
                }
                return this.___DeviceStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DeviceStatus> ___DeviceStatus;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.StockLocation
        {
            get
            {
                return this.StockLocation;
            }
            set
            {
                this.StockLocation = (global::LightSwitchApplication.Implementation.StockLocation)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.StockLocation> __StockLocation
        {
            get
            {
                if (this.___StockLocation == null)
                {
                    this.___StockLocation = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.StockLocation>(
                        this,
                        "StockLocation",
                        new string[] { "Device_StockLocation" },
                        e => global::System.Object.Equals(e.Id, this.Device_StockLocation),
                        () => this._StockLocation,
                        e => this._StockLocation = e);
                }
                return this.___StockLocation;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.StockLocation> ___StockLocation;
        
    }
    #endregion
    
    #region DeviceStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DeviceStatus :
        global::LightSwitchApplication.DeviceStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnTitleChanged()
        {
            this.___OnPropertyChanged("Title");
        }
        
        partial void OnActiveChanged()
        {
            this.___OnPropertyChanged("Active");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DeviceStatus.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> __Devices
        {
            get
            {
                if (this.___Devices == null)
                {
                    this.___Devices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device>(
                        this,
                        "Devices",
                        () => this._Devices,
                        e => global::System.Object.Equals(e.Device_DeviceStatus, this.Id));
                }
                return this.___Devices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> ___Devices;
        
    }
    #endregion
    
    #region HwSwOrder
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class HwSwOrder :
        global::LightSwitchApplication.HwSwOrder.DetailsClass.IImplementation
    {
        partial void OnHwSwOrder_ClientChanged()
        {
            this.___OnPropertyChanged("HwSwOrder_Client");
            this.___OnPropertyChanged("Customer");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnOrderNumberChanged()
        {
            this.___OnPropertyChanged("OrderNumber");
        }
        
        partial void OnAddressChanged()
        {
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnChargeToChanged()
        {
            this.___OnPropertyChanged("ChargeTo");
        }
        
        partial void OnReqiresAppsChanged()
        {
            this.___OnPropertyChanged("ReqiresApps");
        }
        
        partial void OnRequiresKitChanged()
        {
            this.___OnPropertyChanged("RequiresKit");
        }
        
        partial void OnRequiresDeviceChanged()
        {
            this.___OnPropertyChanged("RequiresDevice");
        }
        
        partial void OnTrackingNumberChanged()
        {
            this.___OnPropertyChanged("TrackingNumber");
        }
        
        partial void OnShippedChanged()
        {
            this.___OnPropertyChanged("Shipped");
        }
        
        partial void OnRequestorChanged()
        {
            this.___OnPropertyChanged("Requestor");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.HwSwOrder.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> __Devices
        {
            get
            {
                if (this.___Devices == null)
                {
                    this.___Devices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device>(
                        this,
                        "Devices",
                        () => this._Devices,
                        e => global::System.Object.Equals(e.HwSwOrder_Device, this.Id));
                }
                return this.___Devices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> ___Devices;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.HwSwOrder.DetailsClass.IImplementation.Customer
        {
            get
            {
                return this.Customer;
            }
            set
            {
                this.Customer = (global::LightSwitchApplication.Implementation.Customer)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> __Customer
        {
            get
            {
                if (this.___Customer == null)
                {
                    this.___Customer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer>(
                        this,
                        "Customer",
                        new string[] { "HwSwOrder_Client" },
                        e => global::System.Object.Equals(e.Id, this.HwSwOrder_Client),
                        () => this._Customer,
                        e => this._Customer = e);
                }
                return this.___Customer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Customer> ___Customer;
        
    }
    #endregion
    
    #region MakeModel
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class MakeModel :
        global::LightSwitchApplication.MakeModel.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnMakeChanged()
        {
            this.___OnPropertyChanged("Make");
        }
        
        partial void OnModelChanged()
        {
            this.___OnPropertyChanged("Model");
        }
        
        partial void OnCarrierChanged()
        {
            this.___OnPropertyChanged("Carrier");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MakeModel.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> __Devices
        {
            get
            {
                if (this.___Devices == null)
                {
                    this.___Devices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device>(
                        this,
                        "Devices",
                        () => this._Devices,
                        e => global::System.Object.Equals(e.Device_MakeModel, this.Id));
                }
                return this.___Devices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> ___Devices;
        
    }
    #endregion
    
    #region StockLocation
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class StockLocation :
        global::LightSwitchApplication.StockLocation.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnAddressChanged()
        {
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.StockLocation.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> __Devices
        {
            get
            {
                if (this.___Devices == null)
                {
                    this.___Devices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device>(
                        this,
                        "Devices",
                        () => this._Devices,
                        e => global::System.Object.Equals(e.Device_StockLocation, this.Id));
                }
                return this.___Devices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Device> ___Devices;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Customer))
            {
                return new global::LightSwitchApplication.Implementation.Customer();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Device))
            {
                return new global::LightSwitchApplication.Implementation.Device();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DeviceStatus))
            {
                return new global::LightSwitchApplication.Implementation.DeviceStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.HwSwOrder))
            {
                return new global::LightSwitchApplication.Implementation.HwSwOrder();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.MakeModel))
            {
                return new global::LightSwitchApplication.Implementation.MakeModel();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.StockLocation))
            {
                return new global::LightSwitchApplication.Implementation.StockLocation();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Customer) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Customer);
            }
            if (typeof(global::LightSwitchApplication.Device) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Device);
            }
            if (typeof(global::LightSwitchApplication.DeviceStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DeviceStatus);
            }
            if (typeof(global::LightSwitchApplication.HwSwOrder) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.HwSwOrder);
            }
            if (typeof(global::LightSwitchApplication.MakeModel) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.MakeModel);
            }
            if (typeof(global::LightSwitchApplication.StockLocation) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.StockLocation);
            }
            return null;
        }
    }
}
