//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Inserting(global::LightSwitchApplication.Customer entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Inserted(global::LightSwitchApplication.Customer entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Updating(global::LightSwitchApplication.Customer entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Updated(global::LightSwitchApplication.Customer entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Deleting(global::LightSwitchApplication.Customer entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Deleted(global::LightSwitchApplication.Customer entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Validate(global::LightSwitchApplication.Customer entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Customer, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Inserting(global::LightSwitchApplication.Device entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Inserted(global::LightSwitchApplication.Device entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Updating(global::LightSwitchApplication.Device entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Updated(global::LightSwitchApplication.Device entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Deleting(global::LightSwitchApplication.Device entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Deleted(global::LightSwitchApplication.Device entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Validate(global::LightSwitchApplication.Device entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Devices_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Device, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Inserting(global::LightSwitchApplication.DeviceStatus entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Inserted(global::LightSwitchApplication.DeviceStatus entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Updating(global::LightSwitchApplication.DeviceStatus entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Updated(global::LightSwitchApplication.DeviceStatus entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Deleting(global::LightSwitchApplication.DeviceStatus entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Deleted(global::LightSwitchApplication.DeviceStatus entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Validate(global::LightSwitchApplication.DeviceStatus entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceStatusSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.DeviceStatus, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Inserting(global::LightSwitchApplication.HwSwOrder entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Inserted(global::LightSwitchApplication.HwSwOrder entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Updating(global::LightSwitchApplication.HwSwOrder entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Updated(global::LightSwitchApplication.HwSwOrder entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Deleting(global::LightSwitchApplication.HwSwOrder entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Deleted(global::LightSwitchApplication.HwSwOrder entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Validate(global::LightSwitchApplication.HwSwOrder entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HwSwOrders_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.HwSwOrder, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Inserting(global::LightSwitchApplication.MakeModel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Inserted(global::LightSwitchApplication.MakeModel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Updating(global::LightSwitchApplication.MakeModel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Updated(global::LightSwitchApplication.MakeModel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Deleting(global::LightSwitchApplication.MakeModel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Deleted(global::LightSwitchApplication.MakeModel entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Validate(global::LightSwitchApplication.MakeModel entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MakeModels_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MakeModel, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Inserting(global::LightSwitchApplication.StockLocation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Inserted(global::LightSwitchApplication.StockLocation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Updating(global::LightSwitchApplication.StockLocation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Updated(global::LightSwitchApplication.StockLocation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Deleting(global::LightSwitchApplication.StockLocation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Deleted(global::LightSwitchApplication.StockLocation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Validate(global::LightSwitchApplication.StockLocation entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StockLocations_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StockLocation, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Inserting(global::LightSwitchApplication.Migration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Inserted(global::LightSwitchApplication.Migration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Updating(global::LightSwitchApplication.Migration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Updated(global::LightSwitchApplication.Migration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Deleting(global::LightSwitchApplication.Migration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Deleted(global::LightSwitchApplication.Migration entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Validate(global::LightSwitchApplication.Migration entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Migrations_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Migration, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Customer>
                __CustomersEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Customer>(
                    "Customers",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Customers_Filter);
            private static bool __Customers_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Customers_CanInsert(ref result);
                return result;
            }
            private static bool __Customers_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Customers_CanUpdate(ref result);
                return result;
            }
            private static bool __Customers_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Customers_CanDelete(ref result);
                return result;
            }
            private static bool __Customers_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Customers_CanRead(ref result);
                return result;
            }
            private static void __Customers_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e)
            {
                d.Customers_Inserting(e);
            }
            private static void __Customers_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e)
            {
                d.Customers_Inserted(e);
            }
            private static void __Customers_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e)
            {
                d.Customers_Updating(e);
            }
            private static void __Customers_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e)
            {
                d.Customers_Updated(e);
            }
            private static void __Customers_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e)
            {
                d.Customers_Deleting(e);
            }
            private static void __Customers_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e)
            {
                d.Customers_Deleted(e);
            }
            private static void __Customers_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Customer e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Customers_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Customer, bool>> __Customers_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Customer, bool>> filter = null;
                d.Customers_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Device>
                __DevicesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Device>(
                    "Devices",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Devices_Filter);
            private static bool __Devices_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Devices_CanInsert(ref result);
                return result;
            }
            private static bool __Devices_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Devices_CanUpdate(ref result);
                return result;
            }
            private static bool __Devices_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Devices_CanDelete(ref result);
                return result;
            }
            private static bool __Devices_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Devices_CanRead(ref result);
                return result;
            }
            private static void __Devices_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e)
            {
                d.Devices_Inserting(e);
            }
            private static void __Devices_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e)
            {
                d.Devices_Inserted(e);
            }
            private static void __Devices_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e)
            {
                d.Devices_Updating(e);
            }
            private static void __Devices_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e)
            {
                d.Devices_Updated(e);
            }
            private static void __Devices_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e)
            {
                d.Devices_Deleting(e);
            }
            private static void __Devices_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e)
            {
                d.Devices_Deleted(e);
            }
            private static void __Devices_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Device e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Devices_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Device, bool>> __Devices_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Device, bool>> filter = null;
                d.Devices_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.DeviceStatus>
                __DeviceStatusSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.DeviceStatus>(
                    "DeviceStatusSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DeviceStatusSet_Filter);
            private static bool __DeviceStatusSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DeviceStatusSet_CanInsert(ref result);
                return result;
            }
            private static bool __DeviceStatusSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DeviceStatusSet_CanUpdate(ref result);
                return result;
            }
            private static bool __DeviceStatusSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DeviceStatusSet_CanDelete(ref result);
                return result;
            }
            private static bool __DeviceStatusSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DeviceStatusSet_CanRead(ref result);
                return result;
            }
            private static void __DeviceStatusSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e)
            {
                d.DeviceStatusSet_Inserting(e);
            }
            private static void __DeviceStatusSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e)
            {
                d.DeviceStatusSet_Inserted(e);
            }
            private static void __DeviceStatusSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e)
            {
                d.DeviceStatusSet_Updating(e);
            }
            private static void __DeviceStatusSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e)
            {
                d.DeviceStatusSet_Updated(e);
            }
            private static void __DeviceStatusSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e)
            {
                d.DeviceStatusSet_Deleting(e);
            }
            private static void __DeviceStatusSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e)
            {
                d.DeviceStatusSet_Deleted(e);
            }
            private static void __DeviceStatusSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.DeviceStatus e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.DeviceStatusSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.DeviceStatus, bool>> __DeviceStatusSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.DeviceStatus, bool>> filter = null;
                d.DeviceStatusSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.HwSwOrder>
                __HwSwOrdersEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.HwSwOrder>(
                    "HwSwOrders",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__HwSwOrders_Filter);
            private static bool __HwSwOrders_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HwSwOrders_CanInsert(ref result);
                return result;
            }
            private static bool __HwSwOrders_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HwSwOrders_CanUpdate(ref result);
                return result;
            }
            private static bool __HwSwOrders_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HwSwOrders_CanDelete(ref result);
                return result;
            }
            private static bool __HwSwOrders_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.HwSwOrders_CanRead(ref result);
                return result;
            }
            private static void __HwSwOrders_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e)
            {
                d.HwSwOrders_Inserting(e);
            }
            private static void __HwSwOrders_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e)
            {
                d.HwSwOrders_Inserted(e);
            }
            private static void __HwSwOrders_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e)
            {
                d.HwSwOrders_Updating(e);
            }
            private static void __HwSwOrders_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e)
            {
                d.HwSwOrders_Updated(e);
            }
            private static void __HwSwOrders_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e)
            {
                d.HwSwOrders_Deleting(e);
            }
            private static void __HwSwOrders_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e)
            {
                d.HwSwOrders_Deleted(e);
            }
            private static void __HwSwOrders_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.HwSwOrder e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.HwSwOrders_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.HwSwOrder, bool>> __HwSwOrders_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.HwSwOrder, bool>> filter = null;
                d.HwSwOrders_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MakeModel>
                __MakeModelsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MakeModel>(
                    "MakeModels",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MakeModels_Filter);
            private static bool __MakeModels_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MakeModels_CanInsert(ref result);
                return result;
            }
            private static bool __MakeModels_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MakeModels_CanUpdate(ref result);
                return result;
            }
            private static bool __MakeModels_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MakeModels_CanDelete(ref result);
                return result;
            }
            private static bool __MakeModels_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MakeModels_CanRead(ref result);
                return result;
            }
            private static void __MakeModels_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e)
            {
                d.MakeModels_Inserting(e);
            }
            private static void __MakeModels_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e)
            {
                d.MakeModels_Inserted(e);
            }
            private static void __MakeModels_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e)
            {
                d.MakeModels_Updating(e);
            }
            private static void __MakeModels_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e)
            {
                d.MakeModels_Updated(e);
            }
            private static void __MakeModels_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e)
            {
                d.MakeModels_Deleting(e);
            }
            private static void __MakeModels_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e)
            {
                d.MakeModels_Deleted(e);
            }
            private static void __MakeModels_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MakeModel e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.MakeModels_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MakeModel, bool>> __MakeModels_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MakeModel, bool>> filter = null;
                d.MakeModels_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StockLocation>
                __StockLocationsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StockLocation>(
                    "StockLocations",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StockLocations_Filter);
            private static bool __StockLocations_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StockLocations_CanInsert(ref result);
                return result;
            }
            private static bool __StockLocations_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StockLocations_CanUpdate(ref result);
                return result;
            }
            private static bool __StockLocations_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StockLocations_CanDelete(ref result);
                return result;
            }
            private static bool __StockLocations_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StockLocations_CanRead(ref result);
                return result;
            }
            private static void __StockLocations_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e)
            {
                d.StockLocations_Inserting(e);
            }
            private static void __StockLocations_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e)
            {
                d.StockLocations_Inserted(e);
            }
            private static void __StockLocations_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e)
            {
                d.StockLocations_Updating(e);
            }
            private static void __StockLocations_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e)
            {
                d.StockLocations_Updated(e);
            }
            private static void __StockLocations_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e)
            {
                d.StockLocations_Deleting(e);
            }
            private static void __StockLocations_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e)
            {
                d.StockLocations_Deleted(e);
            }
            private static void __StockLocations_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StockLocation e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.StockLocations_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StockLocation, bool>> __StockLocations_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StockLocation, bool>> filter = null;
                d.StockLocations_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Migration>
                __MigrationsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Migration>(
                    "Migrations",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Migrations_Filter);
            private static bool __Migrations_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Migrations_CanInsert(ref result);
                return result;
            }
            private static bool __Migrations_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Migrations_CanUpdate(ref result);
                return result;
            }
            private static bool __Migrations_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Migrations_CanDelete(ref result);
                return result;
            }
            private static bool __Migrations_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Migrations_CanRead(ref result);
                return result;
            }
            private static void __Migrations_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e)
            {
                d.Migrations_Inserting(e);
            }
            private static void __Migrations_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e)
            {
                d.Migrations_Inserted(e);
            }
            private static void __Migrations_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e)
            {
                d.Migrations_Updating(e);
            }
            private static void __Migrations_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e)
            {
                d.Migrations_Updated(e);
            }
            private static void __Migrations_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e)
            {
                d.Migrations_Deleting(e);
            }
            private static void __Migrations_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e)
            {
                d.Migrations_Deleted(e);
            }
            private static void __Migrations_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Migration e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Migrations_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Migration, bool>> __Migrations_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Migration, bool>> filter = null;
                d.Migrations_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
